### ISSUE TITLE
Update to v0.6.0

### ISSUE THREAD

**Issue by lukasmalkmus** [carlosedp/docker-arm_exporter#3]
Hi Carlos,
could you update to v0.6.0? Got some changes which might be worth updating: https://github.com/lukasmalkmus/rpi_exporter/releases

**Comment by carlosedp** [comment]
Updated and pushed image based on last version from master.
https://cloud.docker.com/u/carlosedp/repository/docker/carlosedp/arm_exporter
Thanks @lukasmalkmus !

**Comment by lukasmalkmus** [comment]
Thanks!
