### ISSUE TITLE
Can't start on armv6 (Raspberry Pi Zero W)

### ISSUE THREAD

**Issue by mhansen** [carlosedp/docker-arm_exporter#9]
Hey there, looks like https://github.com/carlosedp/docker-arm_exporter/commit/52d0771c3cde20ce93e079473227f808b0157f08 removed support for `arm32v6`, replacing it with `linux/arm,linux/arm64`.

I've been using this container for a while on Raspberry Pi Zero W and it's started crashlooping with `Restarting (139) 7 seconds ago`, probably because of an unrecognized ARMv7 instruction.

I don't suppose this would be as simple to fix as adding `linux/arm32v6` like this?

```
    - ARCHS="linux/arm,linux/arm64"
    - ARCHS="linux/arm,linux/arm64,linux/arm/v6"
```

Looks like `linux/arm/v6` is the format according to https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

Btw, thanks for maintaining this, and no worries if you're not interested in supporting ARMv6, I can do a fork - I've gotten a lot of value already out of your image :-)

**Comment by carlosedp** [comment]
I'll take a look into that. It's kinda problem because Golang doesn't provide this image so I'll change the build to provide ARM32V6 as well.

Thanks for reporting

**Comment by mhansen** [comment]
Thank you!

Go's pretty good at cross-compiling - I wonder if there's a simpler way than pulling an entire go ARMv6 builder... (caveat: I don't know much about `docker buildx`).

**Comment by mhansen** [comment]
https://docs.docker.com/buildx/working-with-buildx/ notes that it's possible to use cross-compilation offered by some languages inside `docker buildx`

> Finally, depending on your project, the language that you use may have good support for cross-compilation. In that case, multi-stage builds in Dockerfiles can be effectively used to build binaries for the platform specified with --platform using the native architecture of the build node. A list of build arguments like BUILDPLATFORM and TARGETPLATFORM is available automatically inside your Dockerfile and can be leveraged by the processes running as part of your build.

**Comment by mhansen** [comment]
Their demo looks fairly straightforward for cross-compilation:

```
FROM --platform=$BUILDPLATFORM golang:alpine AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM" > /log
FROM alpine
COPY --from=build /log /log
```

Trouble would be converting docker's platform string `linux/arm/v6` into what go `GOARCH=arm` and optionally `GOARM=6`. Maybe a wrapper script could convert the docker platform string to what go expects.

https://github.com/golang/go/wiki/GoArm

**Comment by mhansen** [comment]
Here's an example wrapper script of someone doing the conversion from docker platform to GOARCH:

https://github.com/tonistiigi/xx/blob/master/golang/wrapper.sh#L26

**Comment by mhansen** [comment]
Oh wow, it looks maybe as simple as adding two lines to your `Dockerfile` to add a wrapper script to `alpine`'s go builder:

https://github.com/tonistiigi/xx/tree/master/golang

Or it'd be pretty easy to take the bits of logic you want and avoid the dep.

**Comment by mhansen** [comment]
Here's an end-to-end example: https://github.com/brocaar/chirpstack-docker/issues/19#issuecomment-525725419

**Comment by mhansen** [comment]
I think I have this working:

https://hub.docker.com/repository/docker/markhnsn/arm_exporter/tags?page=1

Pull request soon

**Comment by carlosedp** [comment]
Thanks!
